name: Monthly GitHub‑Notion asset cleanup

on:
  schedule:
    - cron: '0 18 1 * *'   # 매월 1일 03:00 KST (= 18:00 UTC 전날)
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 자산 삭제
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests

      - name: Run cleanup
        env:
          GH_TOKEN:      ${{ secrets.GH_PAT }}      # repo 삭제 권한 PAT
          NOTION_TOKEN:  ${{ secrets.NOTION_TOKEN }}
          NOTION_DB:     ${{ secrets.NOTION_DB }}
          GH_REPO:       ${{ github.repository }}
        run: python .github/scripts/cleanup_assets.py
